Fix CI failure on 1.43
```
error: failed to get `event-listener` as a dependency of package `async-lock v2.5.0 (/home/runner/work/async-lock/async-lock)`

Caused by:
  failed to load source for dependency `event-listener`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  error reading from the zlib stream; class=Zlib (5)
```